FROM tensorflow/serving:2.4.1

# Leaf the directory of the servable model
# local Structure should be: /1/saved_model.pb
# container structure should be /models/1/saved_model.pb 


# TODO

# 1. Install CURL or Git to download a Sentence Fusion model. 
# 2. Put it in the right directory
# 3. Remove the installer
